### ISSUE TITLE
Showing non-updated DDL for edit

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#112]
If you edit the DDL and save it, then go to a tab such as blobs or demoextras, and finally go back to the DDL page, the shown DDL is not the saved one, but the one that was here when the page was initially loaded. If you do not notice it and start editing the DDL again, you lose all that was done before. (video here https://www.youtube.com/watch?v=hMIa2zgoDTY)

Try to fix this, or ensure that CP2 doesn't have this problem.

**Comment by hmaciasc** [comment]
https://github.com/mcolom/ipolDevel/commit/80c7f900aad79b3b3868b5eae97469a15c6dddaa

This should fix it. I have made it try to prevent using cache through django decorators.
