### ISSUE TITLE
CP: fails to save blob data

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#113]
The current version of the CP is unable to save a blob's info after editing it.

**Comment by hmaciasc** [comment]
https://github.com/mcolom/ipolDevel/commit/14c1df20d6420fe85d6f0b95d6ac808c7597636e
https://github.com/mcolom/ipolDevel/commit/613276b1d3e2e322e2f8afd36c7eb898844a6f78
https://github.com/mcolom/ipolDevel/commit/be3e97bd476e05e483f12e937f1c7971a4633322
https://github.com/mcolom/ipolDevel/commit/5690b8861395d4cd39cc85b870243ba77965d690

**Comment by mcolom** [comment]
Great work, Héctor!
