### ISSUE TITLE
VR not removed even if all blobs were removed

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#116]
There's no way to remove a Visual Representation of a blob, even if all the blobs with that VR have been removed from all demos.
The VR needs to be deleted if it's not associated to any existing blob.

**Comment by hmaciasc** [comment]
https://github.com/mcolom/ipolDevel/commit/5690b8861395d4cd39cc85b870243ba77965d690

**Comment by mcolom** [comment]
Yes, Héctor is on it.
There are several alternatives to solve it. Otherwise, it'll be fixed when we change to the CP2.
