### ISSUE TITLE
Conversion Module: Deal with images .svg and problems in the demo "Zhang-Wu Directional LMMSE Image Demosaicking" 

### ISSUE THREAD

**Issue by nmonzonlo** [mcolom/ipolDevel#18]
This demo generates a png images with problems when we want to make a Thumbnail.

raise IOError("cannot write mode %s as JPEG" % im.mode)
 IOError: cannot write mode P as JPEG

A possible solution is to convert the image to RGB before saving the thumbnail. The code will be:

 img = Image.open(path).convert('RGB')
 img.thumbnail(thumbs_size, Image.ANTIALIAS)

 thumbnail_path = os.path.join(self.work_dir, name_and_extension_for_the_thumbnail)

 img.save(thumbnail_path, "JPEG")

This solutions seems to work with the other demos.

**Comment by mcolom** [comment]
A SVG format is not raster but vectorial.
In any case, this demo was just a test in Integration, so we can close the issue.
