### ISSUE TITLE
Misleading comment or wrong code in base_app.input_select ?

### ISSUE THREAD

**Issue by carlodef** [mcolom/ipolDevel#2]
Hi,

In the `input_select` method of `base_app.py`, the first comment says the opposite of what the next few lines of code do:
 
https://github.com/mcolom/ipolDevel/blob/master/ipol_demo/lib/base_app.py#L441

I think the comment is right: if the key is not empty, the app object needs to be cloned. But the code seems to work as is, so I am surely missing something.

**Comment by mcolom** [comment]
Hi Carlo,
thanks for noting this.

It's the comment which was wrong.
The rationale is: if the key is empty it means that it's a new (normal) execution and a new object is created. If a key exists when we arrive to the method it means that it corresponds to an already known thread and we need to reuse it, not clone it.

Thus, the code is right. I've rewritten the comment as:
        # When we arrive here, self.key should be empty.
        # If not, it means that the execution belongs to another thread
        # and therefore we need to reuse the app object

Best,
Miguel

**Comment by carlodef** [comment]
Ok, thank you for the clarification!
Best,
Carlo
