### ISSUE TITLE
[demoInfo] Code indented with tabs and not with the normative four spaces

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#34]
In demoinfo.py the code is indented with tabs and not with the normative Python's four spaces.
Fix, test, commit, and push. And test again in the integration server.

**Comment by mcolom** [comment]
Thanks for solving the issue, Carlos.
Your first one! :+1: 
Closing.

**Comment by mcolom** [comment]
I'm reopening this issue. The file permissions of the demoInfo files are now too permissive:

 mode change 100644 => 100755 ipol_demo/modules/demoinfo/main.py
 mode change 100644 => 100755 ipol_demo/modules/demoinfo/model.py
 mode change 100644 => 100755 ipol_demo/modules/demoinfo/tests/testdemoinfo.py
 mode change 100644 => 100755 ipol_demo/modules/demoinfo/tools.py

For the owner we move from 6=rx (read and execute) to 7 (read, write, execute). That's OK.
For the group we move from 4=r to 5=rx (read and execute). Well, that's OK.
BUT for the others we move also from 4 to 5, that is, we give execution permission to the "others". But we don't want this. Put the permission of "others" to +r-x-w (numeric value 4 again).

**Comment by mcolom** [comment]
I don't know if the push was done, but the perms are still wrong:
 mode change 100644 => 100755 ipol_demo/modules/demoinfo/main.py
 mode change 100644 => 100755 ipol_demo/modules/demoinfo/model.py
 mode change 100644 => 100755 ipol_demo/modules/demoinfo/tests/testdemoinfo.py
 mode change 100644 => 100755 ipol_demo/modules/demoinfo/tools.py

**Comment by mcolom** [comment]
Is this solved? (I think so...) Can you confirm that I can close this issue?

**Comment by CarlosEscobarBlasco** [comment]
yes, it's solved

**Comment by mcolom** [comment]
Great, thanks a lot!
Closing.
