### ISSUE TITLE
Production machine ipol_core without GPG key for nginx

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#35]
After an apt-get update, the following error message is shown:
W: GPG error: http://nginx.org jessie Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62

Why do we need to install the package out of the Debian repositories? As far as I know, it belongs to the official repositories.

In case it's absolutely needed to install it from out of the Debian official repositories (this needs to be well justified), note that the corresponding GPG key has not been installed.

**Comment by martinarevalo8** [comment]
It was installed out of the Debian repositories by mistake. Commented nginx repo urls in /etc/apt/sources.list, then, uninstalled, apt-get update, and installed from Debian repos.

**Comment by mcolom** [comment]
Indeed, thanks!
Closing.
