### ISSUE TITLE
Core (pre)module doesn't find start.sh

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#36]
After stopping and starting all the modules, the terminal complains about not finding start.sh
Indeed, this file is not archived.

>stopall
core  (http://ns3018037.ip-151-80-24.eu:8080/) is shut down.
demorunner  (http://ns3018037.ip-151-80-24.eu:9004/) is shut down.
proxy  (http://ns3018037.ip-151-80-24.eu:9003/) is shut down.
demoinfo  (http://ns3018037.ip-151-80-24.eu:9002/) is shut down.
archive  (http://ns3018037.ip-151-80-24.eu:9000/) is shut down.
blobs  (http://ns3018037.ip-151-80-24.eu:9001/) is shut down.

>startall
core started, try to ping it.
demorunner started, try to ping it.
proxy started, try to ping it.
demoinfo started, try to ping it.
archive started, try to ping it.
blobs started, try to ping it.
>bash: /home/ipol/ipolDevel/ipol_demo/start.sh: No such file or directory

After this, the demo system is dead and it needs to be re-run with the screen directly from the server.

**Comment by nmonzonlo** [comment]
I have included a start.sh in this (pre)module. Now, the module can be started from the terminal.

**Comment by nmonzonlo** [comment]
Note that this "start.sh" must be changed if we rename demo.py to core.py (and config files) for the final version of the module.

**Comment by mcolom** [comment]
Thus, let's rename it to core.py now.
It means that you need to change the script and change the non-archived server configuration in both integration and production.
After that, we'll close the issue.

**Comment by mcolom** [comment]
Issue solved. Thanks, Nelson.
Closing.
