### ISSUE TITLE
DemoRunner is not logging correctly

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#39]
The demoRunner module is not logging correctly.
Most of the time it simply prints to stdout instead of logging the errors.

And sometimes it's using the totally outdated cherrypy.log functions instead of its own logging system. For example:
cherrypy.log("building", context='SETUP/%s' % demo_id, traceback=False)

It should log all errors. When they happen inside a try/catch, use the logger.exception(...) function to write the full stracktrace.

As part of this issue, all modules should be checked to ensure that they do log properly.

**Comment by mcolom** [comment]
Remember to tell me in a comment here when this is solved. I think it's already finished, but let an explicit comment here.

**Comment by CarlosEscobarBlasco** [comment]
Ok, I'll do It. And yes, this one is finished

**Comment by mcolom** [comment]
Perfect, thanks!
Closing the issue, then.
