### ISSUE TITLE
Core fails because it imports a non-existing "run_demo_base" module

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#40]
When the Core is run (./demo.py), it tries to import the "run_demo_base" Python module, but it doesn't exist:
Traceback (most recent call last):
  File "./demo.py", line 13, in <module>
    from lib import base_app
  File "/home/miguel/ipolDevel/ipol_demo/lib/__init__.py", line 7, in <module>
    from .base_app import base_app
  File "/home/miguel/ipolDevel/ipol_demo/lib/base_app.py", line 42, in <module>
    import  run_demo_base
ImportError: No module named run_demo_base

In fact, it works by chance in both the Integration and Production servers simply because an outdated precompiled file exists:
21:21:38 {prod} ~/ipolDevel$ find . |grep -i run_demo_base
./ipol_demo/modules/demorunner/Tools/run_demo_base.pyc
./ipol_demo/modules/demorunner/Tools/run_demo_base.py
./ipol_demo/lib/run_demo_base.pyc

To reproduce the problem: remove all .pyc files from the Core and execute it.

**Comment by nmonzonlo** [comment]
The core does not need to import base_app anymore. We can remove "from lib import base_app" from the demo.py

**Comment by mcolom** [comment]
Good, thanks!
To close this issue, do the following:

- Of course, first commit, push, pull.
- Stop the core and all modules
- Remove all .pyc files in the integration server (use a find with the --exec option, for example)
- Restart everything.

And check that everything is fine. And we close the issue.

**Comment by mcolom** [comment]
Tested in integration: works.
Closing the issue.
