### ISSUE TITLE
clientApp: wrong execution time display

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#41]
Checked in demo #70 with the following parameters:
URL: http://ipolcore.ipol.im:8080/clientApp/ipol_demo.html?id=70 (production)
Threshold type: manual
tmix, tmax = 25, 91
m = 1911
e=48
Checkbox: marked

After the execution finished, it shows "success (ran in 1.2 s)", but it took more than 30 s.

**Comment by karlkrissian** [comment]
30 second is probably not the execution time but the full time you waited, and includes downloading the archive and compiling if it was not updated

**Comment by mcolom** [comment]
It could be some connection problem, also.
I don't observe the bad timing any more. Thus, I'm closing the issue. Thanks anyway.
