### ISSUE TITLE
DDL LaTeX doc: does not compile

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#42]
The DDL LaTeX documentation does not compile.

{master} ~/ipolDevel/doc/ddl$ pdflatex ddl.tex
[...]
! Package Listings Error: File ` ../../ipol_demo/static/JQueryApp/ipol(.drawblo
bs.js)' not found.
(and similar errors).

**Comment by karlkrissian** [comment]
Should be compiling again (renamed JQueryApp to clientApp)

**Comment by mcolom** [comment]
It does. Thanks.
Closing.
