### ISSUE TITLE
JQuery code: using experimental FormData object

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#45]
The JQuery code is using an object of type FormData, which actually has only experimental support.

http://stackoverflow.com/questions/34712929/formdata-has-is-not-a-function
https://developer.mozilla.org/en-US/docs/Web/API/FormData#Browser_compatibility

It fails if some Chrome versions when it calls the set method. Actually, there's no support for Internet Explorer, Safari, and Opera and we can't use this object at all!

The good news is that its usage is isolated in the file ipol.rundemo.js:
16:10:53 (master) ~/ipolDevel/ipol_demo/modules/core/static/clientApp$ grep -ri "form_data.set"
ipol.rundemo.js:                form_data.set("input_type","upload");
ipol.rundemo.js:                        form_data.set("input_type","blobset");
ipol.rundemo.js:                        form_data.set("input_type","upload");
ipol.rundemo.js:                        form_data.set("input_type","noinputs");

It's absolutely necessary to avoid using this object!

**Comment by karlkrissian** [comment]
After looking in internet, it is true that the set() method is not compatible with several browsers but the append() method is compatible, so it should be possible to avoid the set() and only use append(), the only thing to care about is to use append() only once for a given key.

**Comment by mcolom** [comment]
I don't think it's a problem of certain methods, but of the whole FormData object which is not supported by some browsers: https://developer.mozilla.org/en-US/docs/Web/API/FormData#Browser_compatibility

Thus, the only safe solution is to completely avoid using it.

**Comment by karlkrissian** [comment]
Yes you can see from this page that there is a basic support for most browsers, which is enough to use it

**Comment by mcolom** [comment]
Since the usage of the object is minimal, we'll for the moment avoid using the experimental methods (such as set and others). If the support is not guarantied in the short future we'll simple avoid using it.

**Comment by mcolom** [comment]
Final decision: keep the object and simply avoid using the methods which are not supported.

**Comment by CarlosEscobarBlasco** [comment]
Done! all not supported method removed
