### ISSUE TITLE
CP: fails to upload a large file with demoExtras

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#50]
When a large file is uploaded to the CP to be added to a demo as demoExtras, it simple reloads the page after the upload, but no file is actually uploaded.
It seems that the code is correct and the problem is related to the server configuration (maximum allowed size for upload, probably).

**Comment by CarlosEscobarBlasco** [comment]
Solved

**Comment by mcolom** [comment]
Indeed. It works now. Thanks!
Closing.
