### ISSUE TITLE
Compilation: does not check if the DDL changed once compiled

### ISSUE THREAD

**Issue by mcolom** [mcolom/ipolDevel#61]
The system only checks if the package with the sources is updated before launching a compilation. However, it should start a compilation also if the DDL has changed, even if the sources packages have not.

**Comment by mcolom** [comment]
Actually Jérémy Anger proposed a better idea: "I think there's a better way to handle this one: check if there is a difference (or just hashes) in the build section, instead of having the user to click on a recompile button".

**Comment by mcolom** [comment]
Great this is fixed, thanks!
Could you tell us which is the commit, so the team can do its team review?

**Comment by kidanger** [comment]
It is fixed since we decided to use the docker demorunner from now on.
